from .audit import AuditLogView
from .auth import LoginView, LogoutView
from .ci_workflows import (
    StepDetailView,
    StepsCatalogView,
    StepsRepoDetailView,
    StepsRepoListView,
    StepsRepoRegisterView,
    StepsRepoScanStatusView,
    StepsRepoScanView,
    StepsTableView,
)
from .connections import (
    ConnectionConfigUpdateView,
    ConnectionCreateDispatchView,
    ConnectionDeleteView,
    ConnectionDetailView,
    ConnectionListView,
    ConnectionTestView,
    PluginListView,
)
from .dashboard import DashboardView
from .env_vars import (
    EnvVarBulkSaveView,
)
from .groups import (
    GroupAddMemberView,
    GroupCreateView,
    GroupDeleteView,
    GroupDetailView,
    GroupEditView,
    GroupListView,
    GroupRemoveMemberView,
)
from .projects import (
    AddMemberModalView,
    EnvironmentAttachConnectionView,
    EnvironmentCreateView,
    EnvironmentDeleteView,
    EnvironmentDetachConnectionView,
    EnvironmentDetailView,
    EnvironmentUpdateView,
    ProjectApproveWorkflowView,
    ProjectArchiveView,
    ProjectAttachConnectionView,
    ProjectCIConfigView,
    ProjectCreateModalView,
    ProjectCreateView,
    ProjectDetachConnectionView,
    ProjectDetailView,
    ProjectListView,
    ProjectRemoveApprovedWorkflowView,
    ProjectUpdateCIConfigView,
    ProjectUpdateView,
    RemoveMemberView,
)
from .settings import (
    ApiTokensView,
    AuditLogsSettingsView,
    CIConfigSettingsView,
    GeneralSettingsView,
    NotificationsView,
    UserManagementView,
)
from .setup import UnlockView
from .templates import (
    TemplateDeregisterView,
    TemplateDetailView,
    TemplateListView,
    TemplateRegisterView,
    TemplateSyncStatusView,
)
from .users import UserCreateView, UserDeleteView, UserEditView, UserListView

__all__ = [
    "AddMemberModalView",
    "ApiTokensView",
    "AuditLogView",
    "AuditLogsSettingsView",
    "CIConfigSettingsView",
    "ConnectionConfigUpdateView",
    "ConnectionCreateDispatchView",
    "ConnectionDeleteView",
    "ConnectionDetailView",
    "ConnectionListView",
    "ConnectionTestView",
    "DashboardView",
    "EnvVarBulkSaveView",
    "EnvironmentAttachConnectionView",
    "EnvironmentCreateView",
    "EnvironmentDeleteView",
    "EnvironmentDetachConnectionView",
    "EnvironmentDetailView",
    "EnvironmentUpdateView",
    "GeneralSettingsView",
    "GroupAddMemberView",
    "GroupCreateView",
    "GroupDeleteView",
    "GroupDetailView",
    "GroupEditView",
    "GroupListView",
    "GroupRemoveMemberView",
    "LoginView",
    "LogoutView",
    "NotificationsView",
    "PluginListView",
    "ProjectApproveWorkflowView",
    "ProjectArchiveView",
    "ProjectAttachConnectionView",
    "ProjectCIConfigView",
    "ProjectCreateModalView",
    "ProjectCreateView",
    "ProjectDetachConnectionView",
    "ProjectDetailView",
    "ProjectListView",
    "ProjectRemoveApprovedWorkflowView",
    "ProjectUpdateCIConfigView",
    "ProjectUpdateView",
    "RemoveMemberView",
    "StepDetailView",
    "StepsCatalogView",
    "StepsRepoDetailView",
    "StepsRepoListView",
    "StepsRepoRegisterView",
    "StepsRepoScanStatusView",
    "StepsRepoScanView",
    "StepsTableView",
    "TemplateDeregisterView",
    "TemplateDetailView",
    "TemplateListView",
    "TemplateRegisterView",
    "TemplateSyncStatusView",
    "UnlockView",
    "UserCreateView",
    "UserDeleteView",
    "UserEditView",
    "UserListView",
    "UserManagementView",
]
