from .audit import AuditLogView
from .auth import LoginView, LogoutView
from .ci_workflows import (
    RuntimesView,
    StepDetailView,
    StepsCatalogView,
    StepsRepoDetailView,
    StepsRepoListView,
    StepsRepoRegisterView,
    StepsRepoScanStatusView,
    StepsRepoScanView,
)
from .connections import (
    ConnectionConfigUpdateView,
    ConnectionCreateDispatchView,
    ConnectionDeleteView,
    ConnectionDetailView,
    ConnectionListView,
    ConnectionTestView,
    PluginListView,
)
from .dashboard import DashboardView
from .groups import (
    GroupAddMemberView,
    GroupCreateView,
    GroupDeleteView,
    GroupDetailView,
    GroupEditView,
    GroupListView,
    GroupRemoveMemberView,
)
from .placeholders import ResourcesPlaceholderView, ServicesPlaceholderView
from .projects import (
    AddMemberModalView,
    EnvironmentAttachConnectionView,
    EnvironmentCreateView,
    EnvironmentDeleteView,
    EnvironmentDetachConnectionView,
    EnvironmentDetailView,
    EnvironmentUpdateView,
    EnvVarDeleteView,
    EnvVarModalView,
    EnvVarSaveView,
    ProjectArchiveView,
    ProjectAttachConnectionView,
    ProjectCreateModalView,
    ProjectCreateView,
    ProjectDetachConnectionView,
    ProjectDetailView,
    ProjectEnvVarDeleteView,
    ProjectEnvVarModalView,
    ProjectEnvVarSaveView,
    ProjectListView,
    ProjectUpdateView,
    RemoveMemberView,
)
from .settings import (
    ApiTokensView,
    AuditLogsSettingsView,
    GeneralSettingsView,
    NotificationsView,
    UserManagementView,
)
from .setup import UnlockView
from .users import UserCreateView, UserDeleteView, UserEditView, UserListView

__all__ = [
    "UnlockView",
    "LoginView",
    "LogoutView",
    "DashboardView",
    "UserListView",
    "UserCreateView",
    "UserEditView",
    "UserDeleteView",
    "GroupListView",
    "GroupDetailView",
    "GroupCreateView",
    "GroupEditView",
    "GroupDeleteView",
    "GroupAddMemberView",
    "GroupRemoveMemberView",
    "AuditLogView",
    "ServicesPlaceholderView",
    "ResourcesPlaceholderView",
    "ConnectionListView",
    "ConnectionDetailView",
    "ConnectionTestView",
    "ConnectionDeleteView",
    "ConnectionConfigUpdateView",
    "ConnectionCreateDispatchView",
    "PluginListView",
    "ProjectListView",
    "ProjectCreateModalView",
    "ProjectCreateView",
    "ProjectDetailView",
    "ProjectUpdateView",
    "ProjectArchiveView",
    "EnvironmentCreateView",
    "EnvironmentDetailView",
    "EnvironmentUpdateView",
    "EnvironmentDeleteView",
    "AddMemberModalView",
    "RemoveMemberView",
    "ProjectEnvVarModalView",
    "ProjectEnvVarSaveView",
    "ProjectEnvVarDeleteView",
    "EnvVarModalView",
    "EnvVarSaveView",
    "EnvVarDeleteView",
    "ProjectAttachConnectionView",
    "ProjectDetachConnectionView",
    "EnvironmentAttachConnectionView",
    "EnvironmentDetachConnectionView",
    "GeneralSettingsView",
    "UserManagementView",
    "AuditLogsSettingsView",
    "ApiTokensView",
    "NotificationsView",
    # CI Workflows
    "StepsRepoListView",
    "StepsRepoRegisterView",
    "StepsRepoDetailView",
    "StepsRepoScanView",
    "StepsRepoScanStatusView",
    "StepsCatalogView",
    "StepDetailView",
    "RuntimesView",
]
