# Generated by Django 6.0.1 on 2026-01-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_ciworkflow_stepsrepository_cistep_ciworkflowstep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
