# Generated by Django 6.0.1 on 2026-01-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_group_external_id_alter_user_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciworkflow",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("draft", "Draft")], default="published", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_manifest_pr_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_manifest_pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_manifest_status",
            field=models.CharField(
                choices=[("never_pushed", "Never Pushed"), ("synced", "Synced"), ("out_of_date", "Out of Date")],
                default="never_pushed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.ciworkflow",
            ),
        ),
        migrations.CreateModel(
            name="ProjectCIConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approve_all_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_projects",
                        to="core.ciworkflow",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ci_config", to="core.project"
                    ),
                ),
            ],
            options={
                "db_table": "core_project_ci_config",
            },
        ),
        migrations.CreateModel(
            name="ProjectApprovedWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approved_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_workflows",
                        to="core.project",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_approvals",
                        to="core.ciworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "core_project_approved_workflow",
                "unique_together": {("project", "workflow")},
            },
        ),
    ]
