# Generated by Django 6.0.1 on 2026-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_ciworkflow_status_service_ci_manifest_pr_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cistep",
            name="engine",
            field=models.CharField(default="github_actions", help_text="CI engine this step belongs to", max_length=63),
        ),
        migrations.AddField(
            model_name="stepsrepository",
            name="engine",
            field=models.CharField(
                default="github_actions", help_text="CI engine identifier, e.g., github_actions", max_length=63
            ),
        ),
    ]
