# Generated by Django 6.0.1 on 2026-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_cistep_engine_stepsrepository_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciworkflow",
            name="dev_workflow",
            field=models.CharField(
                choices=[("trunk_based", "Trunk-Based Development")],
                default="trunk_based",
                help_text="Development workflow pattern",
                max_length=50,
            ),
        ),
    ]
