# Generated by Django 6.0.1 on 2026-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_ciworkflow_dev_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="scaffold_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
