# Generated by Django 6.0.1 on 2026-02-03 13:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_not_required_scaffold_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("github_run_id", models.BigIntegerField(db_index=True, unique=True)),
                ("run_number", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                ("commit_message", models.TextField(blank=True)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("author", models.CharField(blank=True, max_length=150)),
                ("author_avatar_url", models.URLField(blank=True, max_length=500)),
                ("ci_job_url", models.URLField(blank=True, max_length=500)),
                ("artifact_ref", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="builds", to="core.service"
                    ),
                ),
            ],
            options={
                "db_table": "core_build",
                "ordering": ["-created_at"],
            },
        ),
    ]
