# Generated by Django 6.0.1 on 2026-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="webhook_registered",
            field=models.BooleanField(default=False),
        ),
    ]
