# Generated by Django 6.0.1 on 2026-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_service_webhook_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="failed_job_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="build",
            name="failed_step_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
