# Generated by Django 6.0.1 on 2026-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_build_failed_step_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="workflow_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
