# Generated by Django 6.0.1 on 2026-02-11 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_add_workflow_name_to_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="manifest_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="build",
            name="manifest_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="build",
            name="verification_status",
            field=models.CharField(
                blank=True,
                choices=[("verified", "Verified"), ("draft", "Draft"), ("unauthorized", "Unauthorized")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="projectciconfig",
            name="allow_draft_workflows",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, services in this project can use draft workflow versions for pipeline testing in non-production environments.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_manifest_push_method",
            field=models.CharField(
                choices=[("pr", "Pull Request"), ("direct", "Direct Push")], default="pr", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="CIWorkflowVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("authorized", "Authorized"), ("revoked", "Revoked")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("manifest_hash", models.CharField(blank=True, max_length=64)),
                ("manifest_content", models.TextField(blank=True)),
                ("changelog", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="core.ciworkflow"
                    ),
                ),
            ],
            options={
                "db_table": "core_ci_workflow_version",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="build",
            name="workflow_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="builds",
                to="core.ciworkflowversion",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_workflow_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_services",
                to="core.ciworkflowversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="ciworkflowversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")), fields=("workflow",), name="unique_draft_per_workflow"
            ),
        ),
        migrations.AddConstraint(
            model_name="ciworkflowversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version", ""), _negated=True),
                fields=("workflow", "version"),
                name="unique_version_per_workflow",
            ),
        ),
    ]
