# Generated by Django 6.0.1 on 2026-02-16 11:55

from django.db import migrations, models


def rename_out_of_date(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    Service.objects.filter(ci_manifest_status="out_of_date").update(ci_manifest_status="out_of_sync")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_ci_workflow_version"),
    ]

    operations = [
        migrations.RunPython(rename_out_of_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="service",
            name="ci_manifest_push_method",
            field=models.CharField(choices=[("pr", "Pull Request")], default="pr", max_length=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="ci_manifest_status",
            field=models.CharField(
                choices=[
                    ("never_pushed", "Never Pushed"),
                    ("pending_pr", "Pending PR"),
                    ("synced", "Synced"),
                    ("out_of_sync", "Out of Sync"),
                ],
                default="never_pushed",
                max_length=20,
            ),
        ),
    ]
