# Generated by Django 6.0.1 on 2026-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_rename_manifest_status_out_of_sync_add_pending_pr"),
    ]

    operations = [
        migrations.AddField(
            model_name="cistep",
            name="file_path",
            field=models.CharField(
                blank=True, help_text="Relative path from repo root to the step definition file", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="cistep",
            name="last_change_type",
            field=models.CharField(
                blank=True,
                choices=[("interface", "Interface"), ("metadata", "Metadata")],
                help_text="Type of change detected in the last scan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cistep",
            name="slug",
            field=models.CharField(
                blank=True, help_text="URL-safe identifier derived from x-pathfinder.name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cistep",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="cistep",
            constraint=models.UniqueConstraint(fields=("engine", "slug"), name="unique_step_slug_per_engine"),
        ),
    ]
