# Generated by Django 6.0.1 on 2026-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_cistep_file_path_cistep_last_change_type_cistep_slug_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cistep",
            unique_together=set(),
        ),
    ]
