# Generated by Django 6.0.1 on 2026-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_cistep_directory_name_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciworkflow",
            name="engine",
            field=models.CharField(
                default="github_actions", help_text="CI engine identifier, set at creation and immutable", max_length=63
            ),
        ),
        migrations.AlterField(
            model_name="ciworkflow",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("draft", "Draft"), ("archived", "Archived")],
                default="published",
                max_length=20,
            ),
        ),
    ]
