# Generated by Django 6.0.1 on 2026-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_add_engine_and_archived_to_ciworkflow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="build",
            old_name="github_run_id",
            new_name="ci_run_id",
        ),
        migrations.AlterField(
            model_name="build",
            name="verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verified", "Verified"),
                    ("draft", "Draft"),
                    ("revoked", "Revoked"),
                    ("unauthorized", "Unauthorized"),
                ],
                max_length=16,
            ),
        ),
    ]
