# Generated by Django 6.0.1 on 2026-02-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_rename_github_run_id_build_ci_run_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepsrepository",
            name="last_scanned_sha",
            field=models.CharField(blank=True, help_text="Commit SHA of the last successful scan", max_length=40),
        ),
        migrations.AddField(
            model_name="stepsrepository",
            name="protection_valid",
            field=models.BooleanField(
                default=False, help_text="Whether branch protection rules are satisfied on the default branch"
            ),
        ),
        migrations.CreateModel(
            name="StepsRepoSyncLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                ("previous_sha", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("protection_valid", models.BooleanField(default=False)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("webhook", "Webhook"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("steps_added", models.IntegerField(default=0)),
                ("steps_updated", models.IntegerField(default=0)),
                ("steps_archived", models.IntegerField(default=0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to="core.stepsrepository"
                    ),
                ),
            ],
            options={
                "db_table": "core_steps_repo_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StepSyncEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("step_slug", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("updated", "Updated"),
                            ("archived", "Archived"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="core.stepsreposynclog"
                    ),
                ),
            ],
            options={
                "db_table": "core_step_sync_entry",
                "ordering": ["id"],
            },
        ),
    ]
