# Generated by Django 6.0.1 on 2026-02-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_stepsrepository_last_scanned_sha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="auto_update_patch",
            field=models.BooleanField(
                default=True, help_text="Automatically update CI manifest when a patch version is published"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="last_cleanup_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp of last version cleanup run", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="version_retention_days",
            field=models.IntegerField(
                default=365, help_text="Days before manifest content is cleared from old versions"
            ),
        ),
    ]
