# Generated by Django 6.0.1 on 2026-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ci_variables_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="ci_variables_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("provisioned", "Provisioned"), ("failed", "Failed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
