# Generated by Django 6.0.1 on 2026-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_service_ci_variables_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciworkflow",
            name="runtime_constraints",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Derived runtime version constraints from composed steps. E.g., {'python': '>=3.11', 'node': '>=18'}",
            ),
        ),
        migrations.AlterField(
            model_name="ciworkflow",
            name="runtime_family",
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name="ciworkflow",
            name="runtime_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
