# Generated by Django 6.0.1 on 2026-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_ciworkflow_runtime_constraints_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cistep",
            name="outputs_schema",
            field=models.JSONField(
                default=dict, help_text="Output declarations from step definition (e.g., action.yml outputs block)"
            ),
        ),
    ]
