# Generated by Django 6.0.1 on 2026-02-24 14:38

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_cistep_outputs_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="template_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="DNS-compatible name from pathfinder.yaml manifest.",
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_dns_label",
                                message="Name must be DNS-compatible: lowercase letters, numbers, and hyphens only. Max 63 characters, no leading/trailing hyphens.",
                                regex="^[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$|^[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("git_url", models.URLField(max_length=500)),
                ("runtimes", models.JSONField(default=list)),
                ("required_vars", models.JSONField(default=dict)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sync_error", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_sha", models.CharField(blank=True, max_length=40)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="core.integrationconnection",
                    ),
                ),
            ],
            options={
                "db_table": "core_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplateConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="template_config", to="core.project"
                    ),
                ),
                (
                    "allowed_templates",
                    models.ManyToManyField(blank=True, related_name="allowed_in_projects", to="core.template"),
                ),
                (
                    "default_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_projects",
                        to="core.template",
                    ),
                ),
            ],
            options={
                "db_table": "core_project_template_config",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.template",
            ),
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=100)),
                ("commit_sha", models.CharField(max_length=40)),
                ("available", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("sort_key", models.CharField(blank=True, max_length=100)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="core.template"
                    ),
                ),
            ],
            options={
                "db_table": "core_template_version",
                "ordering": ["-sort_key"],
                "unique_together": {("template", "tag_name")},
            },
        ),
    ]
