# Generated by Django 6.0.1 on 2026-02-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_ciworkflowstep_step_commit_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="key_prefix",
            field=models.CharField(blank=True, default="", help_text="First 8 chars for identification", max_length=8),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="key",
            field=models.CharField(db_index=True, help_text="SHA-256 hash of the token", max_length=64, unique=True),
        ),
    ]
