# Generated by Django 6.0.1 on 2026-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_api_token_key_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="endpoint",
            field=models.URLField(
                blank=True, help_text="Service endpoint URL (e.g. https://api.example.com)", max_length=500
            ),
        ),
    ]
