# Generated by Django 6.0.1 on 2026-03-22 12:55

from django.db import migrations, models


def backfill_setup_completed(apps, schema_editor):
    """Set setup_completed=True for existing installations.

    Checks the DB-side evidence of a completed setup: an active 'admins'
    group with at least one member (created by the registration view).
    Fresh installs have no groups yet so they stay False.
    """
    Group = apps.get_model("core", "Group")
    GroupMembership = apps.get_model("core", "GroupMembership")
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")

    admins = Group.objects.filter(name="admins", status="active").first()
    if admins and GroupMembership.objects.filter(group=admins).exists():
        config, _ = SiteConfiguration.objects.get_or_create(pk=1)
        config.setup_completed = True
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_service_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="setup_completed",
            field=models.BooleanField(
                default=False, help_text="Set once during initial unlock. Prevents re-entering the setup wizard."
            ),
        ),
        migrations.RunPython(backfill_setup_completed, migrations.RunPython.noop),
    ]
