apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pathfinder.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
data:
  django-debug: {{ .Values.config.djangoDebug | quote }}
  allowed-hosts: {{ .Values.config.allowedHosts | quote }}
  csrf-trusted-origins: {{ .Values.config.csrfTrustedOrigins | quote }}
