{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pathfinder.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "pathfinder.fullname" .) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "django-secret-key") }}
  django-secret-key: {{ index $existingSecret.data "django-secret-key" }}
  {{- else if .Values.secrets.djangoSecretKey }}
  django-secret-key: {{ .Values.secrets.djangoSecretKey | b64enc }}
  {{- else }}
  django-secret-key: {{ randAlphaNum 50 | b64enc }}
  {{- end }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "encryption-key") }}
  encryption-key: {{ index $existingSecret.data "encryption-key" }}
  {{- else if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc }}
  {{- else }}
  encryption-key: {{ randBytes 32 | b64enc }}
  {{- end }}
{{- end }}
