{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pathfinder.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "pathfinder.postgresql.fullname" .) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "postgresql-password") }}
  postgresql-password: {{ index $existingSecret.data "postgresql-password" }}
  {{- else if .Values.postgresql.auth.password }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
{{- end }}
