name: CI - test
'on':
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Notify SSP - Build Started
      uses: ./ci-steps/ssp-notify-start
    - name: Setup Python
      uses: yourdevops/ci-steps-library/ci-steps/setup-python@8c670e1c21e0c762fb15183a78f1390f1db71a5e
    - name: Lint with Ruff
      uses: yourdevops/ci-steps-library/ci-steps/lint-ruff@8c670e1c21e0c762fb15183a78f1390f1db71a5e
    - name: Security Scan
      uses: yourdevops/ci-steps-library/ci-steps/security-scan@8c670e1c21e0c762fb15183a78f1390f1db71a5e
    - name: Test with pytest
      uses: yourdevops/ci-steps-library/ci-steps/test-pytest@8c670e1c21e0c762fb15183a78f1390f1db71a5e
    - name: Notify SSP - Build Complete
      uses: ./ci-steps/ssp-notify-complete
