name: python-uv CI workflow
'on':
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python with uv
      uses: yourdevops/ci-steps-library/ci-steps/setup-python-uv@ce87e11fefada8560d310b73566b7e68d9e10fb8
    - name: Lint with Ruff
      uses: yourdevops/ci-steps-library/ci-steps/lint-ruff@ce87e11fefada8560d310b73566b7e68d9e10fb8
